- name: Setup Tomcat8 & Deploy Artifact
  hosts: appsrvgrp
  become: yes
  vars:
    timestamp: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}_{{ansible_date_time.minute}}"

  tasks:
    - name: Download latest VProfile.war from Nexus
      get_url:
        url: "http://{{USER}}:{{PASS}}@{{nexusip}}:8081/repository/{{reponame}}/{{groupid}}/{{artifactid}}/{{build_version}}/{{artifactid}}-{{build_version}}.war"
        dest: "/tmp/{{artifactid}}-{{build_version}}.war"
      register: wardeploy
      tags:
        - deploy

    - name: Stop Tomcat service
      service:
        name: tomcat
        state: stopped
      tags:
        - deploy

    - name: Check if current ROOT directory exists
      stat:
        path: /usr/local/tomcat8/webapps/ROOT
      register: artifact_stat
      tags:
        - deploy

    - name: Backup current ROOT
      block:
        - name: Archive ROOT dir with timestamp
          archive:
            path: /usr/local/tomcat8/webapps/ROOT
            dest: "/opt/ROOT_{{timestamp}}.tgz"
          when: artifact_stat.stat.exists
          register: archive_info

        - name: Delete current artifact
          file:
            path: "{{item}}"
            state: absent
          loop:
            - /usr/local/tomcat8/webapps/ROOT
            - /usr/local/tomcat8/webapps/ROOT.war
          when: archive_info is defined and archive_info.changed

    - name: Deploy new artifact
      copy:
        src: "/tmp/{{artifactid}}-{{build_version}}.war"
        dest: /usr/local/tomcat8/webapps/ROOT.war
        remote_src: yes
      register: deploy_info

    - name: Start Tomcat service
      service:
        name: tomcat
        state: started
      when: deploy_info.changed

    - name: Wait until ROOT.war is extracted
      wait_for:
        path: /usr/local/tomcat8/webapps/ROOT

    - name: Deploy web configuration file
      template:
        src: templates/application.j2
        dest: /usr/local/tomcat8/webapps/ROOT/WEB-INF/classes/application.properties
        force: yes
      notify:
        - Restart Tomcat

  handlers:
    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted